### PR TITLE
Added Promise alternative to "getSendTransaction"

### PR DESCRIPTION
**Pull request by alex-ppg**
Hey go-faast,

I wanted to add a Promise alternative to your `getSendTransaction` function that is not "balance-safe" and does not check to ensure the user has enough balance to transact. I thought you might find it useful, within the branch I tried to follow your code-style as much as possible (no ";" at the end of lines etc.) and I also added a test-case for the new `Promise` function.

### CODE REVIEW

**Comment by moeadham** [comment]
Thanks For the PR! I wonder if this should just be a new function, or if we should make the balance check an optional flag to allow non-promise implementations also have the option.

Can you give a bit more detail why you want only this function to return promises? Do you not need promises on other functions as well?

**Comment by alex-ppg** [comment]
Hey moaedham, sorry for the late response.

The balance check should be optional in my opinion as it allows offline signing, which is also the reason I required it. 

With regards to the function returning a `Promise`, this is the only function I am currently using from the library. I would prefer if the library would be capable of both promises and callback-style executions to satisfy both worlds. 

I can make more commits and transform the other functions as well & add a flag for checking the balance or not, although I personally think that should not be the case as the transaction would fail when broadcasted anyway. It's just my schedule is a bit packed this week so it'll be some time.

**Comment by alex-ppg** [comment]
Hello @moeadham once again,

I extended the library a bit. I wrapped all `function`s with a callback in `Promise`s via introspection (Checking if a variable named "done" exists in the function's arguments). I also split `getSendTransaction` to `sendTransaction` (on-line) and `signTransaction` (off-line), the former being the same as yours whilst the latter being my alteration. I also assigned `sendTransaction` to `getSendTransaction` to ensure backwards compatibility.

Let me know your thoughts.

**Comment by moeadham** [comment]
Awesome! I’ll test and merge if there aren’t any issues.

**Comment by dylanseago** [comment]
Hey @alex-ppg, thank you very much for your contribution. The library has since been entirely restructured to use promises and a separate signTransaction method, similar to your contribution. I hope this fits your needs.

**Pull request closed without merging**
